#! /usr/bin/python
# -*- coding: utf-8 -*-
#author: David Quesada López

"""
Small script that unifies in a single file all the ones generated by de webscraper.
"""

import sys  
import os

def unify():
	n = len(os.listdir('./descripciones'))
	i = 1
	res = open('InfoPisos', 'w')
	
	while i <= n:
		doc = open('descripciones/'+str(i), 'r')
		info = doc.read().replace('\n', '') # Some files have a \n and some don't
		doc.close()
		res.write('id-' + str(i) + ' ; ' + info + '\n')
		i += 1

reload(sys)  
sys.setdefaultencoding('utf8')
unify()
